version: '3.8'

services:
  postgres:
    image: "pgvector/pgvector:pg16"
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data: