spring:
  application:
    name: spring-ai-rag-pgvector-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db
    username: user
    password: password
  ai:
    openai:
      api-key: ${OPEN_AI_TOKEN}
      chat:
        options.model: ${OPEN_AI_MODEL}
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000

